### ISSUE TITLE
A few issues, but still the best mod!

### ISSUE THREAD

**Issue by Fellow9000** [NoteBoxz/LethalMin#9]
A few things I've encountered with the Pikmin is they can't seem to pick up those fancy lamp items, and they struggle with carrying soccer balls unless they're thrown directly on top of them, otherwise they kick it around. One the manor moons, throwing a Pikmin on a table would have them get stuck on top until thrown or after exiting the facility. 
Also, using the whistle through open secure doors in the facility would block the sound's range until passing through the doorway.
Some of these issues may just be from mods on my end and might not be an issue otherwise.

Aside from that, this is the best mod I've ever played! I've enjoyed commanding this army of Pikmin and breezing through the dungeons, knowing full well that they could all disappear in a moment's notice. The ability to efficiently move scrap back towards the ship while clearing the way is exciting and keeps me invested in this engaging challenge.

And finally, would we be able to expect new Pikmin or ways to feed the Onion to produce an army? Also, the Pikmin container is a bit large and hard to fit in the ship's layout, would there be a way to shrink it or have something that would fit snug in a corner?

Many thanks, and I wish you the best!

**Comment by NoteBoxz** [comment]
Thanks for your input! Some of the issues you've listed are things that I'm not really sure I can fix.
Like the Pikmin getting stuck on tables is an issue with Lethal Company's NavMeshes not having a way for entities to get on or off of objects like tables, while still having a nav mesh surface on them.

I'll have to look into it more, but I'm not sure if entities are even intended to be able to pick up the soccer ball due to its wonky physics.

The other issues you've listed are things are things that are coming to the next update (V0.2.0) The Pikmin Container is getting redesigned, The Onion will be able to produce Pikmin instead of just containing them, and the whistle/throwing trajectory doorway issue will be looked into.

**Comment by Fellow9000** [comment]
Alright, thank you!

**Comment by NoteBoxz** [comment]
V0.2.0
